### ISSUE TITLE
Task List - Lab #2

### ISSUE THREAD

**Issue by apurbaanik** [apurbaanik/topStreamedArtists#1]
Task List:
- [x] Create a repository
- [x] Add topStreamedArtists.java
- [x] Create a README file with a description.
- [x] Add the input and output files.
- [x] Submit the link in MS Teams.

**Comment by apurbaanik** [comment]
Uploaded source code, input, and output files.

**Comment by apurbaanik** [comment]
Submitted on MS teams.
